name: "Stale Teams check"

on:
  schedule:
    - cron:  '* * * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    name: A job to check stale prs/issues
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: stale-teams
      id: stale-teams
      uses: ./
      with:
        webhook: ${{ secrets.webhook }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 2